<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array>
    <string>twl2</string>
   </array>
  <key>name</key>
  <string>twl2</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.twl2</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(grammar\s*\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.twl2</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.twl2</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(actions\s*{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.twl2</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.twl2</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>action</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\b[a-zA-Z][a-zA-Z0-9.\-_]*)(\(.*\))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.twl2</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.language.twl2</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(-&gt;)</string>
          <key>name</key>
          <string>keyword.operator.implication.twl2</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#rsh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\|)([^\x{0023}]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.given.twl2</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.language.twl2</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(#)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.twl2</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.twl2</string>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>none.twl2</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>comment__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>grammar</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>(\b[a-zA-Z][a-zA-Z0-9.\-_]*)</string>
          <key>name</key>
          <string>entity.name.function.twl2</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(-&gt;)</string>
          <key>name</key>
          <string>keyword.operator.implication.twl2</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#rsh</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\|)([^\x{0023}]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.given.twl2</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.language.twl2</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>listSymbol</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.twl2</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#listSymbol__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.twl2</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>listSymbol__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#specialSymbol</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#nonTerminalSymbol</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#grammar</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#action</string>
        </dict>
       </array>
    </dict>
    <key>nonTerminalSymbol</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(&lt;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.other.inherited-class.twl2</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.other.inherited-class.twl2</string>
          <key>end</key>
          <string>(&gt;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.other.inherited-class.twl2</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>nonTerminalSymbol__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>rsh</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.twl2</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array>
            <dict>
              <key>include</key>
              <string>#rsh__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.twl2</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>rsh__1</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#listSymbol</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#specialSymbol</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#nonTerminalSymbol</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#text</string>
        </dict>
       </array>
    </dict>
    <key>specialSymbol</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>({)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.twl2</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>variable.parameter.twl2</string>
          <key>end</key>
          <string>(})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.parameter.twl2</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>specialSymbol__1</key>
    <dict>
      <key>patterns</key>
      <array>
       </array>
    </dict>
    <key>text</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>([^\x{007b}\x{007d}\[\]\x{003c}\x{003e}\x{0022}]+)</string>
          <key>name</key>
          <string>string.twl2</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
