#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by TatSu.
#
#    https://pypi.python.org/pypi/tatsu/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.

from __future__ import print_function, division, absolute_import, unicode_literals

from tatsu.objectmodel import Node
from tatsu.semantics import ModelBuilderSemantics


class ModelBase(Node):
    pass


class TWL2ModelBuilderSemantics(ModelBuilderSemantics):
    def __init__(self, context=None, types=None):
        types = [
            t for t in globals().values()
            if type(t) is type and issubclass(t, ModelBase)
        ] + (types or [])
        super(TWL2ModelBuilderSemantics, self).__init__(context=context, types=types)


class Literal(ModelBase):
    value = None


class TerminalSymbol(ModelBase):
    literal = None


class NonterminalSymbol(ModelBase):
    symbol = None


class EvalSymbol(ModelBase):
    statement = None


class ConditionalSymbol(ModelBase):
    expression = None
    given = None


class SpecialSymbol(ModelBase):
    statement = None


class ListSymbol(ModelBase):
    symbols = None


class AdjectiveNoun(ModelBase):
    adjective = None
    noun = None


class Match(ModelBase):
    lhs = None
    rhs = None


class String(ModelBase):
    symbols = None


class ProductionRule(ModelBase):
    alternatives = None
    symbol = None


class PlaceholderNode(ModelBase):
    name = None
    type = None


class PredicateNode(ModelBase):
    name = None
    parameters = None


class ExpressionNode(ModelBase):
    expression = None


class ConjunctionNode(ModelBase):
    expressions = None


class DisjunctionNode(ModelBase):
    expressions = None


class RhsNode(ModelBase):
    given = None
    symbols = None


class RuleNode(ModelBase):
    lhs = None
    rhs = None


class GrammarNode(ModelBase):
    rules = None


class ActionNode(ModelBase):
    feedback = None
    name = None
    template = None


class ActionsNode(ModelBase):
    actions = None


class TWL2Document(ModelBase):
    actions = None
    grammar = None
